from tkinter import *
from example import *

class BoardFrame:
    global tileArray

    tileArray = []
    def updateLabelText(label):
        if (example.backEndCheck()):
            if (label['text'] == "Player " + p1Name + "'s turn"):
                label.configure(text = "Player " + p2Name + "'s turn")
            else:
                label.configure(text = "Player " + p1Name + "'s turn")
               
    def scrabbleBoard(root, frame, player1Name, player2Name):
        #Hide the playerInput grid
        frame.grid_remove()
        #Storing the names of players for the turn label.
        global p1Name, p2Name
        p1Name = player1Name
        p2Name = player2Name

        #Creating the frame that the Scrabble game is played on.
        boardF = Frame(root)
        boardF.grid(row = 0,column = 0)
        #Creating labels for the outside of the board.
        #Creating empty label for spacing purposes.
        emptyL1 = Label(boardF, text = " ")
        emptyL1.grid(row = 0, column = 0)
        #Loop that creates the labels for the columns of the board.
        for col in range(1, 16):
            boardLabel(boardF, 0, col, str(col-1))
        #Loop that creates the labels for the rows of the board.
        for row in range(1, 16):
            boardLabel(boardF, row, 0, str(row-1))

        #Loop that creates the buttons that make up the board of the game.


        #Creating the side panel for playing the game.
        #Creating a turn label that tells which player's turn it currently is.
        turnL = Label(boardF, text = "Player " + str(p1Name) + "'s turn")
        turnL.grid(row = 2, column = 17)
        #Creating labels for the player's score
        p1ScoreL = Label(boardF, text = str(p1Name) + "'s Score")
        p1ScoreL.grid(row = 3, column = 17)
        p2ScoreL = Label(boardF, text = str(p2Name) + "'s Score")
        p2ScoreL.grid(row = 3, column = 18)
        #labels for the values of the score
        p1ScoreValL = Label(boardF, text = "num")
        p1ScoreValL.grid(row = 4, column = 17)
        p2ScoreValL = Label(boardF, text = "num")
        p2ScoreValL.grid(row = 4, column = 18)
        #Buttons for end move and exchange tiles.
        exchangeTileB = Button(boardF, text = "Exchange Tiles")
        exchangeTileB.grid(row = 11, column = 18)
        endMoveB = Button(boardF, text = "End Move", command=lambda: BoardFrame.updateLabelText(turnL))
        endMoveB.grid(row = 11, column = 17)

        #empty label as a buffer
        emptyL2 = Label(boardF, text = " ")
        emptyL2.grid(row = 0,column = 16,rowspan = 15)
        #The label and input for word, row, column and direction.
        inputWordL = Label(boardF, text = "Enter word")
        inputWordL.grid(row = 7, column = 17)
        inputWordE = Entry(boardF)
        inputWordE.grid(row = 7, column = 18)
        inputRowL = Label(boardF, text = "Enter row")
        inputRowL.grid(row = 8, column = 17)
        inputRowE = Entry(boardF)
        inputRowE.grid(row = 8, column = 18)
        inputColL = Label(boardF, text = "Enter column")
        inputColL.grid(row = 9, column = 17 )
        inputColE = Entry(boardF)
        inputColE.grid(row = 9, column = 18)
        inputDirL = Label(boardF, text = "Enter direction")
        inputDirL.grid(row = 10, column = 17)
        inputDirE = Entry(boardF)
        inputDirE.grid(row = 10, column = 18)

        #i_word = inputWordE.get()

        for row in range(1, 16):
            tileRow = []
            for column in  range(1, 16):
                tile = ColorButton(boardF, "floral white", row, column, "")
                tileRow.append(tile)
            tileArray.append(tileRow)

        tileArray[0][0].configure("text", "TWS")
        tileArray[0][0].configure("bg", "LightGoldenrod1")
        tileArray[0][3].configure("text", "DLS")
        tileArray[0][3].configure("bg", "Light Blue")
        tileArray[0][7].configure("text", "TWS")
        tileArray[0][7].configure("bg", "LightGoldenrod1")
        tileArray[0][11].configure("text", "DLS")
        tileArray[0][11].configure("bg", "Light Blue")
        tileArray[0][14].configure("text", "TWS")
        tileArray[0][14].configure("bg", "LightGoldenrod1")
        
        tileArray[1][1].configure("text", "DWS")
        tileArray[1][1].configure("bg", "Pink")
        tileArray[1][5].configure("text", "TLS")
        tileArray[1][5].configure("bg", "pale green")
        tileArray[1][9].configure("text", "TLS")
        tileArray[1][9].configure("bg", "pale green")
        tileArray[1][13].configure("text", "DWS")
        tileArray[1][13].configure("bg", "Pink")
        
        tileArray[2][2].configure("text", "DWS")
        tileArray[2][2].configure("bg", "Pink")
        tileArray[2][6].configure("text", "DLS")
        tileArray[2][6].configure("bg", "Light Blue")
        tileArray[2][8].configure("text", "DLS")
        tileArray[2][8].configure("bg", "Light Blue")
        tileArray[2][12].configure("text", "DWS")
        tileArray[2][12].configure("bg", "Pink")
        
        tileArray[3][0].configure("text", "DLS")
        tileArray[3][0].configure("bg", "Light Blue")
        tileArray[3][3].configure("text", "DWS")
        tileArray[3][3].configure("bg", "Pink")
        tileArray[3][7].configure("text", "DLS")
        tileArray[3][7].configure("bg", "Light Blue")
        tileArray[3][11].configure("text", "DWS")
        tileArray[3][11].configure("bg", "Pink")
        tileArray[3][14].configure("text", "DLS")
        tileArray[3][14].configure("bg", "Light Blue")
        
        tileArray[4][4].configure("text", "DWS")
        tileArray[4][4].configure("bg", "Pink")
        tileArray[4][10].configure("text", "DWS")
        tileArray[4][10].configure("bg", "Pink")
        
        tileArray[5][1].configure("text", "TLS")
        tileArray[5][1].configure("bg", "pale green")
        tileArray[5][5].configure("text", "TLS")
        tileArray[5][5].configure("bg", "pale green")
        tileArray[5][9].configure("text", "TLS")
        tileArray[5][9].configure("bg", "pale green")
        tileArray[5][13].configure("text", "TLS")
        tileArray[5][13].configure("bg", "pale green")
        
        tileArray[6][2].configure("text", "DLS")
        tileArray[6][2].configure("bg", "Light Blue")
        tileArray[6][6].configure("text", "DLS")
        tileArray[6][6].configure("bg", "Light Blue")
        tileArray[6][8].configure("text", "DLS")
        tileArray[6][8].configure("bg", "Light Blue")
        tileArray[6][12].configure("text", "DLS")
        tileArray[6][12].configure("bg", "Light Blue")
        
        tileArray[7][0].configure("text", "TWS")
        tileArray[7][0].configure("bg", "LightGoldenrod1")
        tileArray[7][3].configure("text", "DLS")
        tileArray[7][3].configure("bg", "Light Blue")
        tileArray[7][7].configure("text", "★")
        tileArray[7][7].configure("bg", "Pink")
        tileArray[7][11].configure("text", "DLS")
        tileArray[7][11].configure("bg", "Light Blue")
        tileArray[7][14].configure("text", "TWS")
        tileArray[7][14].configure("bg", "LightGoldenrod1")
        
        tileArray[8][2].configure("text", "DLS")
        tileArray[8][2].configure("bg", "Light Blue")
        tileArray[8][6].configure("text", "DLS")
        tileArray[8][6].configure("bg", "Light Blue")
        tileArray[8][8].configure("text", "DLS")
        tileArray[8][8].configure("bg", "Light Blue")
        tileArray[8][12].configure("text", "DLS")
        tileArray[8][12].configure("bg", "Light Blue")
        
        tileArray[9][1].configure("text", "TLS")
        tileArray[9][1].configure("bg", "pale green")
        tileArray[9][5].configure("text", "TLS")
        tileArray[9][5].configure("bg", "pale green")
        tileArray[9][9].configure("text", "TLS")
        tileArray[9][9].configure("bg", "pale green")
        tileArray[9][13].configure("text", "TLS")
        tileArray[9][13].configure("bg", "pale green")
        
        tileArray[10][4].configure("text", "DWS")
        tileArray[10][4].configure("bg", "Pink")
        tileArray[10][10].configure("text", "DWS")
        tileArray[10][10].configure("bg", "Pink")
        
        tileArray[11][0].configure("text", "DLS")
        tileArray[11][0].configure("bg", "Light Blue")
        tileArray[11][3].configure("text", "DWS")
        tileArray[11][3].configure("bg", "Pink")
        tileArray[11][7].configure("text", "DLS")
        tileArray[11][7].configure("bg", "Light Blue")
        tileArray[11][11].configure("text", "DWS")
        tileArray[11][11].configure("bg", "Pink")
        tileArray[11][14].configure("text", "DLS")
        tileArray[11][14].configure("bg", "Light Blue")
        
        tileArray[12][2].configure("text", "DWS")
        tileArray[12][2].configure("bg", "Pink")
        tileArray[12][6].configure("text", "DLS")
        tileArray[12][6].configure("bg", "Light Blue")
        tileArray[12][8].configure("text", "DLS")
        tileArray[12][8].configure("bg", "Light Blue")
        tileArray[12][12].configure("text", "DWS")
        tileArray[12][12].configure("bg", "Pink")
        
        tileArray[13][1].configure("text", "DWS")
        tileArray[13][1].configure("bg", "Pink")
        tileArray[13][5].configure("text", "TLS")
        tileArray[13][5].configure("bg", "pale green")
        tileArray[13][9].configure("text", "TLS")
        tileArray[13][9].configure("bg", "pale green")
        tileArray[13][13].configure("text", "DWS")
        tileArray[13][13].configure("bg", "Pink")
        
        tileArray[14][0].configure("text", "TWS")
        tileArray[14][0].configure("bg", "LightGoldenrod1")
        tileArray[14][3].configure("text", "DLS")
        tileArray[14][3].configure("bg", "Light Blue")
        tileArray[14][7].configure("text", "TWS")
        tileArray[14][7].configure("bg", "LightGoldenrod1")
        tileArray[14][11].configure("text", "DLS")
        tileArray[14][11].configure("bg", "Light Blue")
        tileArray[14][14].configure("text", "TWS")
        tileArray[14][14].configure("bg", "LightGoldenrod1")
        

        #Manually colouring and adding text to premium squares.
        # B00 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        # B03 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B07 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        # B011 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")

        #Creating the buttons to represent the board of the Scrabble game.
        #B00 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        #B01 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B02 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B03 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        #B04 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B05 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B06 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B07 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        #B08 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B09 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B010 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B011 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        #B012 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B013 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #B014 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")

        #B00.grid(row = 1, column = 1)
        #B01.grid(row = 1, column = 2)
        #B02.grid(row = 1, column = 3)
        #B03.grid(row = 1, column = 4)
        #B04.grid(row = 1, column = 5)
        #B05.grid(row = 1, column = 6)
        #B06.grid(row = 1, column = 7)
        #B07.grid(row = 1, column = 8)
        #B08.grid(row = 1, column = 9)
        #B09.grid(row = 1, column = 10)
        #B010.grid(row = 1, column = 11)
        #B011.grid(row = 1, column = 12)
        #B012.grid(row = 1, column = 13)
        #B013.grid(row = 1, column = 14)
        #B014.grid(row = 1, column = 15)

        # B10 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B11 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B12 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B13 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B14 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B15 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B16 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B17 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B18 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B19 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B110 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B111 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B112 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B113 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B114 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B10.grid(row = 2, column = 1)
        # B11.grid(row = 2, column = 2)
        # B12.grid(row = 2, column = 3)
        # B13.grid(row = 2, column = 4)
        # B14.grid(row = 2, column = 5)
        # B15.grid(row = 2, column = 6)
        # B16.grid(row = 2, column = 7)
        # B17.grid(row = 2, column = 8)
        # B18.grid(row = 2, column = 9)
        # B19.grid(row = 2, column = 10)
        # B110.grid(row = 2, column = 11)
        # B111.grid(row = 2, column = 12)
        # B112.grid(row = 2, column = 13)
        # B113.grid(row = 2, column = 14)
        # B114.grid(row = 2, column = 15)
        #
        # B20 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B21 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B22 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B23 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B24 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B25 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B26 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B27 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B28 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B29 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B210 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B211 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B212 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B213 = Button(boardF, height = 3, width = 6, state=DISABLED, text ="")
        # B214 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B20.grid(row = 3, column = 1)
        # B21.grid(row = 3, column = 2)
        # B22.grid(row = 3, column = 3)
        # B23.grid(row = 3, column = 4)
        # B24.grid(row = 3, column = 5)
        # B25.grid(row = 3, column = 6)
        # B26.grid(row = 3, column = 7)
        # B27.grid(row = 3, column = 8)
        # B28.grid(row = 3, column = 9)
        # B29.grid(row = 3, column = 10)
        # B210.grid(row = 3, column = 11)
        # B211.grid(row = 3, column = 12)
        # B212.grid(row = 3, column = 13)
        # B213.grid(row = 3, column = 14)
        # B214.grid(row = 3, column = 15)
        #
        # B30 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B31 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B32 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B33 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B34 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B35 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B36 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B37 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B38 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B39 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B310 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B311 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B312 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B313 = Button(boardF, height = 3, width = 6, state=DISABLED, text ="")
        # B314 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        #
        # B30.grid(row = 4, column = 1)
        # B31.grid(row = 4, column = 2)
        # B32.grid(row = 4, column = 3)
        # B33.grid(row = 4, column = 4)
        # B34.grid(row = 4, column = 5)
        # B35.grid(row = 4, column = 6)
        # B36.grid(row = 4, column = 7)
        # B37.grid(row = 4, column = 8)
        # B38.grid(row = 4, column = 9)
        # B39.grid(row = 4, column = 10)
        # B310.grid(row = 4, column = 11)
        # B311.grid(row = 4, column = 12)
        # B312.grid(row = 4, column = 13)
        # B313.grid(row = 4, column = 14)
        # B314.grid(row = 4, column = 15)
        #
        # B40 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B41 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B42 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B43 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B44 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B45 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B46 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B47 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B48 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B49 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B410 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B411 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B412 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B413 = Button(boardF, height = 3, width = 6, state=DISABLED, text ="")
        # B414 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B40.grid(row = 5, column = 1)
        # B41.grid(row = 5, column = 2)
        # B42.grid(row = 5, column = 3)
        # B43.grid(row = 5, column = 4)
        # B44.grid(row = 5, column = 5)
        # B45.grid(row = 5, column = 6)
        # B46.grid(row = 5, column = 7)
        # B47.grid(row = 5, column = 8)
        # B48.grid(row = 5, column = 9)
        # B49.grid(row = 5, column = 10)
        # B410.grid(row = 5, column = 11)
        # B411.grid(row = 5, column = 12)
        # B412.grid(row = 5, column = 13)
        # B413.grid(row = 5, column = 14)
        # B414.grid(row = 5, column = 15)
        #
        # B50 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B51 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B52 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B53 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B54 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B55 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B56 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B57 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B58 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B59 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B510 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B511 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B512 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B513 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B514 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B50.grid(row = 6, column = 1)
        # B51.grid(row = 6, column = 2)
        # B52.grid(row = 6, column = 3)
        # B53.grid(row = 6, column = 4)
        # B54.grid(row = 6, column = 5)
        # B55.grid(row = 6, column = 6)
        # B56.grid(row = 6, column = 7)
        # B57.grid(row = 6, column = 8)
        # B58.grid(row = 6, column = 9)
        # B59.grid(row = 6, column = 10)
        # B510.grid(row = 6, column = 11)
        # B511.grid(row = 6, column = 12)
        # B512.grid(row = 6, column = 13)
        # B513.grid(row = 6, column = 14)
        # B514.grid(row = 6, column = 15)
        #
        # B60 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B61 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B62 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B63 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B64 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B65 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B66 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B67 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B68 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B69 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B610 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B611 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B612 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B613 = Button(boardF, height = 3, width = 6, state=DISABLED, text ="")
        # B614 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B60.grid(row = 7, column = 1)
        # B61.grid(row = 7, column = 2)
        # B62.grid(row = 7, column = 3)
        # B63.grid(row = 7, column = 4)
        # B64.grid(row = 7, column = 5)
        # B65.grid(row = 7, column = 6)
        # B66.grid(row = 7, column = 7)
        # B67.grid(row = 7, column = 8)
        # B68.grid(row = 7, column = 9)
        # B69.grid(row = 7, column = 10)
        # B610.grid(row = 7, column = 11)
        # B611.grid(row = 7, column = 12)
        # B612.grid(row = 7, column = 13)
        # B613.grid(row = 7, column = 14)
        # B614.grid(row = 7, column = 15)
        #
        # B70 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        # B71 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B72 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B73 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B74 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B75 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B76 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B77 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "*")
        # B78 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B79 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B710 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B711 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B712 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B713 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B714 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        #
        # B70.grid(row = 8, column = 1)
        # B71.grid(row = 8, column = 2)
        # B72.grid(row = 8, column = 3)
        # B73.grid(row = 8, column = 4)
        # B74.grid(row = 8, column = 5)
        # B75.grid(row = 8, column = 6)
        # B76.grid(row = 8, column = 7)
        # B77.grid(row = 8, column = 8)
        # B78.grid(row = 8, column = 9)
        # B79.grid(row = 8, column = 10)
        # B710.grid(row = 8, column = 11)
        # B711.grid(row = 8, column = 12)
        # B712.grid(row = 8, column = 13)
        # B713.grid(row = 8, column = 14)
        # B714.grid(row = 8, column = 15)
        #
        # B80 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B81 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B82 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B83 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B84 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B85 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B86 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B87 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B88 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B89 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B810 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B811 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B812 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B813 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B814 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B80.grid(row = 9, column = 1)
        # B81.grid(row = 9, column = 2)
        # B82.grid(row = 9, column = 3)
        # B83.grid(row = 9, column = 4)
        # B84.grid(row = 9, column = 5)
        # B85.grid(row = 9, column = 6)
        # B86.grid(row = 9, column = 7)
        # B87.grid(row = 9, column = 8)
        # B88.grid(row = 9, column = 9)
        # B89.grid(row = 9, column = 10)
        # B810.grid(row = 9, column = 11)
        # B811.grid(row = 9, column = 12)
        # B812.grid(row = 9, column = 13)
        # B813.grid(row = 9, column = 14)
        # B814.grid(row = 9, column = 15)
        #
        # B90 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B91 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B92 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B93 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B94 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B95 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B96 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B97 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B98 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B99 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B910 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B911 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B912 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B913 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B914 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B90.grid(row = 10, column = 1)
        # B91.grid(row = 10, column = 2)
        # B92.grid(row = 10, column = 3)
        # B93.grid(row = 10, column = 4)
        # B94.grid(row = 10, column = 5)
        # B95.grid(row = 10, column = 6)
        # B96.grid(row = 10, column = 7)
        # B97.grid(row = 10, column = 8)
        # B98.grid(row = 10, column = 9)
        # B99.grid(row = 10, column = 10)
        # B910.grid(row = 10, column = 11)
        # B911.grid(row = 10, column = 12)
        # B912.grid(row = 10, column = 13)
        # B913.grid(row = 10, column = 14)
        # B914.grid(row = 10, column = 15)
        #
        # B100 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B101 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B102 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B103 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B104 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B105 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B106 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B107 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B108 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B109 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1010 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B1011 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1012 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1013 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1014 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B100.grid(row = 11, column = 1)
        # B101.grid(row = 11, column = 2)
        # B102.grid(row = 11, column = 3)
        # B103.grid(row = 11, column = 4)
        # B104.grid(row = 11, column = 5)
        # B105.grid(row = 11, column = 6)
        # B106.grid(row = 11, column = 7)
        # B107.grid(row = 11, column = 8)
        # B108.grid(row = 11, column = 9)
        # B109.grid(row = 11, column = 10)
        # B1010.grid(row = 11, column = 11)
        # B1011.grid(row = 11, column = 12)
        # B1012.grid(row = 11, column = 13)
        # B1013.grid(row = 11, column = 14)
        # B1014.grid(row = 11, column = 15)
        #
        # B110 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B111 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B112 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B113 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B114 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B115 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B116 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B117 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B118 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B119 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1110 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1111 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B1112 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1113 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1114 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        #
        # B110.grid(row = 12, column = 1)
        # B111.grid(row = 12, column = 2)
        # B112.grid(row = 12, column = 3)
        # B113.grid(row = 12, column = 4)
        # B114.grid(row = 12, column = 5)
        # B115.grid(row = 12, column = 6)
        # B116.grid(row = 12, column = 7)
        # B117.grid(row = 12, column = 8)
        # B118.grid(row = 12, column = 9)
        # B119.grid(row = 12, column = 10)
        # B1110.grid(row = 12, column = 11)
        # B1111.grid(row = 12, column = 12)
        # B1112.grid(row = 12, column = 13)
        # B1113.grid(row = 12, column = 14)
        # B1114.grid(row = 12 , column = 15)
        #
        # B120 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B121 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B122 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS" )
        # B123 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B124 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B125 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B126 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B127 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B128 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS", )
        # B129 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1210 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1211 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1212 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B1213 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1214 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B120.grid(row = 13, column = 1)
        # B121.grid(row = 13, column = 2)
        # B122.grid(row = 13, column = 3)
        # B123.grid(row = 13, column = 4)
        # B124.grid(row = 13, column = 5)
        # B125.grid(row = 13, column = 6)
        # B126.grid(row = 13, column = 7)
        # B127.grid(row = 13, column = 8)
        # B128.grid(row = 13, column = 9)
        # B129.grid(row = 13, column = 10)
        # B1210.grid(row = 13, column = 11)
        # B1211.grid(row = 13, column = 12)
        # B1212.grid(row = 13, column = 13)
        # B1213.grid(row = 13, column = 14)
        # B1214.grid(row = 13, column = 15)
        #
        # B130 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B131 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B132 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B133 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B134 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B135 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B136 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B137 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B138 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B139 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Purple", text = "TLS")
        # B1310 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1311 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1312 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1313 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Pink", text = "DWS")
        # B1314 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        #
        # B130.grid(row = 14, column = 1)
        # B131.grid(row = 14, column = 2)
        # B132.grid(row = 14, column = 3)
        # B133.grid(row = 14, column = 4)
        # B134.grid(row = 14, column = 5)
        # B135.grid(row = 14, column = 6)
        # B136.grid(row = 14, column = 7)
        # B137.grid(row = 14, column = 8)
        # B138.grid(row = 14, column = 9)
        # B139.grid(row = 14, column = 10)
        # B1310.grid(row = 14, column = 11)
        # B1311.grid(row = 14, column = 12)
        # B1312.grid(row = 14, column = 13)
        # B1313.grid(row = 14, column = 14)
        # B1314.grid(row = 14, column = 15)
        #
        # B140 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        # B141 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B142 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B143 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B144 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B145 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B146 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B147 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        # B148 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B149 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1410 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1411 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Light Blue", text = "DLS")
        # B1412 = Button(boardF, height = 3, width = 6, state=DISABLED, text = "")
        # B1413 = Button(boardF, height = 3, width = 6, state=DISABLED, text ="")
        # B1414 = Button(boardF, height = 3, width = 6, state=DISABLED, bg = "Red", text = "TWS")
        #
        # B140.grid(row = 15, column = 1)
        # B141.grid(row = 15, column = 2)
        # B142.grid(row = 15, column = 3)
        # B143.grid(row = 15, column = 4)
        # B144.grid(row = 15, column = 5)
        # B145.grid(row = 15, column = 6)
        # B146.grid(row = 15, column = 7)
        # B147.grid(row = 15, column = 8)
        # B148.grid(row = 15, column = 9)
        # B149.grid(row = 15, column = 10)
        # B1410.grid(row = 15, column = 11)
        # B1411.grid(row = 15, column = 12)
        # B1412.grid(row = 15, column = 13)
        # B1413.grid(row = 15, column = 14)
        # B1414.grid(row = 15, column = 15)


class boardLabel:
    def __init__(self, frame, row, column, text):
        self.frame = frame
        self.row = row
        self.column = column
        self.text = text

        self.label = Label(self.frame, text = self.text)
        self.label.grid(row = self.row, column = self.column)

class ColorButton:
        def __init__(self, frame, colour, row, column, text):
            self.frame = frame
            self.colour = colour
            self.row = row
            self.column = column
            self.text = text

            if colour == "":
                self.button = Button(self.frame, height = 2, width = 6, state = DISABLED, text=self.text)
            else:
                self.button = Button(self.frame, height = 2, width = 6, state = DISABLED, bg = self.colour, text=self.text)


            self.button.grid(row = self.row, column = self.column)
        def configure(self, attribute, text):
            self.button[attribute] = text
